FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY vehicle_position_consumer.py .

# Run the consumer application
CMD ["python", "vehicle_position_consumer.py"]